# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    main: main.go
    ldflags:
      - "-X cmd/commands.version={{.Version}}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ .Version }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
