package tpl

var (
	CzToml = `[tool.commitizen]
  version = "0.0.0"`

	GoreleaserYaml = `# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  -
    main: ./cmd/api
    env:
      - CGO_ENABLED=0
    goos:
      - "linux"

archives:
  - replacements:
      linux: Linux

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'`

	ReadmeMd = `# {{Name}}

Generated engine service.`

	MainGo = `package main

  import (
    "github.com/Drafteame/framework/engine"
    "{{Namespace}}/internal/routes"
  )

  func main() {
    app := engine.NewApp()

    app.Start(func(a engine.App) {
      routes.Register(a)
    })
  }`

	RoutesGo = `// Automatically generated by engine. DO NOT EDIT.
package routes

import "github.com/Drafteame/framework/engine"

func Register(app engine.App) {
  // router:register
}`

	GoMod = `module {{Namespace}}

go 1.17`

	Makefile = `help: ## Display this help screen.
  @grep -h -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

install: ## Install all dependencies for Go and Serverless framework
  @go mod download && go mod tidy

build: clean ## Build the project binary
  @sh ./build.sh

clean: ## Clean generated binaries
  @rm -rf ./bin

test: ## Execute unit testing
  @go test -v -race` + " `" + `go list ./... | grep -v node_modules` + "`" + `

lint: ## Lint code
  @golangci-lint run ./...

run: ## Execute stand alone local server
  @go run ./cmd/api/main.go`

	GolangCIYaml = `run:
  timeout: 5m
  skip-files:
    - generated.*

issues:
  new: true

linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - unparam
    - varcheck
    - whitespace
  disable:
    - errcheck`

	PackageJSON = `{
  "name": "{{Name}}",
  "description": "Service that will handle all related operations of the user",
  "version": "0.0.0",
  "devDependencies": {
    "serverless": "^2.69.1",
    "serverless-domain-manager": "^5.2.0",
    "serverless-plugin-warmup": "^6.0.0"
  }
}`

	GitIgnore = `# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with ` + "`go test -c`" + `
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out
bin/

# Dependency directories (remove the comment below to include it)
# vendor/

# IDE folders
.idea/
.vscode/

# Node modules
node_modules/

# Extra files
.DS_Store`

	GitKeep = ``
)
