name: Pull Request

on:
  pull_request:
    branches:
      - main



jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version: ${{ vars.GO_VERSION_FULL }}

      - name: Run Revive
        uses: morphy2k/revive-action@v2
        with:
          config: revive.toml

      - name: Run go vet
        run: go vet ./...

  commit_lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          token: '${{ secrets.ACCESS_TOKEN }}'
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ vars.PYTHON_VERSION }}

      - name: Install Commitizen
        run: pip install -U commitizen

      - name: Check commits
        run: cz check --rev-range origin/main..HEAD

      - name: Check PR title
        run: cz check -m "${{ github.event.pull_request.title }}"

